/**
 * Plaid API
 * API for accessing financial institution data via Plaid.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlaidApi);
  }
}(this, function(expect, PlaidApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInnerStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SearchInstitutions200ResponseInstitutionsInnerStatus', function() {
    it('should create an instance of SearchInstitutions200ResponseInstitutionsInnerStatus', function() {
      // uncomment below and update the code to test SearchInstitutions200ResponseInstitutionsInnerStatus
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInnerStatus();
      //expect(instance).to.be.a(PlaidApi.SearchInstitutions200ResponseInstitutionsInnerStatus);
    });

    it('should have the property itemLogins (base name: "item_logins")', function() {
      // uncomment below and update the code to test the property itemLogins
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInnerStatus();
      //expect(instance).to.be();
    });

    it('should have the property transactionsUpdates (base name: "transactions_updates")', function() {
      // uncomment below and update the code to test the property transactionsUpdates
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInnerStatus();
      //expect(instance).to.be();
    });

    it('should have the property auth (base name: "auth")', function() {
      // uncomment below and update the code to test the property auth
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInnerStatus();
      //expect(instance).to.be();
    });

    it('should have the property identity (base name: "identity")', function() {
      // uncomment below and update the code to test the property identity
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInnerStatus();
      //expect(instance).to.be();
    });

    it('should have the property investments (base name: "investments")', function() {
      // uncomment below and update the code to test the property investments
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInnerStatus();
      //expect(instance).to.be();
    });

    it('should have the property investmentsUpdates (base name: "investments_updates")', function() {
      // uncomment below and update the code to test the property investmentsUpdates
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInnerStatus();
      //expect(instance).to.be();
    });

    it('should have the property liabilitiesUpdates (base name: "liabilities_updates")', function() {
      // uncomment below and update the code to test the property liabilitiesUpdates
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInnerStatus();
      //expect(instance).to.be();
    });

  });

}));
