/**
 * Plaid API
 * API for accessing financial institution data via Plaid.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlaidApi);
  }
}(this, function(expect, PlaidApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SearchInstitutions200ResponseInstitutionsInner', function() {
    it('should create an instance of SearchInstitutions200ResponseInstitutionsInner', function() {
      // uncomment below and update the code to test SearchInstitutions200ResponseInstitutionsInner
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInner();
      //expect(instance).to.be.a(PlaidApi.SearchInstitutions200ResponseInstitutionsInner);
    });

    it('should have the property institutionId (base name: "institution_id")', function() {
      // uncomment below and update the code to test the property institutionId
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInner();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInner();
      //expect(instance).to.be();
    });

    it('should have the property countryCodes (base name: "country_codes")', function() {
      // uncomment below and update the code to test the property countryCodes
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInner();
      //expect(instance).to.be();
    });

    it('should have the property products (base name: "products")', function() {
      // uncomment below and update the code to test the property products
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInner();
      //expect(instance).to.be();
    });

    it('should have the property routingNumbers (base name: "routing_numbers")', function() {
      // uncomment below and update the code to test the property routingNumbers
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInner();
      //expect(instance).to.be();
    });

    it('should have the property dtcNumbers (base name: "dtc_numbers")', function() {
      // uncomment below and update the code to test the property dtcNumbers
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInner();
      //expect(instance).to.be();
    });

    it('should have the property oauth (base name: "oauth")', function() {
      // uncomment below and update the code to test the property oauth
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInner();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new PlaidApi.SearchInstitutions200ResponseInstitutionsInner();
      //expect(instance).to.be();
    });

  });

}));
