/**
 * Plaid API
 * API for accessing financial institution data via Plaid.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SearchInstitutions200Response from '../model/SearchInstitutions200Response';
import SearchInstitutionsRequest from '../model/SearchInstitutionsRequest';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Search for financial institutions
     * @param {module:model/SearchInstitutionsRequest} searchInstitutionsRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SearchInstitutions200Response} and HTTP response
     */
    searchInstitutionsWithHttpInfo(searchInstitutionsRequest) {
      let postBody = searchInstitutionsRequest;
      // verify the required parameter 'searchInstitutionsRequest' is set
      if (searchInstitutionsRequest === undefined || searchInstitutionsRequest === null) {
        throw new Error("Missing the required parameter 'searchInstitutionsRequest' when calling searchInstitutions");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SearchInstitutions200Response;
      return this.apiClient.callApi(
        '/institutions/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Search for financial institutions
     * @param {module:model/SearchInstitutionsRequest} searchInstitutionsRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SearchInstitutions200Response}
     */
    searchInstitutions(searchInstitutionsRequest) {
      return this.searchInstitutionsWithHttpInfo(searchInstitutionsRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
