/**
 * Plaid API
 * API for accessing financial institution data via Plaid.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SearchInstitutions200ResponseInstitutionsInnerStatus from './SearchInstitutions200ResponseInstitutionsInnerStatus';

/**
 * The SearchInstitutions200ResponseInstitutionsInner model module.
 * @module model/SearchInstitutions200ResponseInstitutionsInner
 * @version 1.0.0
 */
class SearchInstitutions200ResponseInstitutionsInner {
    /**
     * Constructs a new <code>SearchInstitutions200ResponseInstitutionsInner</code>.
     * @alias module:model/SearchInstitutions200ResponseInstitutionsInner
     */
    constructor() { 
        
        SearchInstitutions200ResponseInstitutionsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchInstitutions200ResponseInstitutionsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchInstitutions200ResponseInstitutionsInner} obj Optional instance to populate.
     * @return {module:model/SearchInstitutions200ResponseInstitutionsInner} The populated <code>SearchInstitutions200ResponseInstitutionsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchInstitutions200ResponseInstitutionsInner();

            if (data.hasOwnProperty('institution_id')) {
                obj['institution_id'] = ApiClient.convertToType(data['institution_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('country_codes')) {
                obj['country_codes'] = ApiClient.convertToType(data['country_codes'], ['String']);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], ['String']);
            }
            if (data.hasOwnProperty('routing_numbers')) {
                obj['routing_numbers'] = ApiClient.convertToType(data['routing_numbers'], ['String']);
            }
            if (data.hasOwnProperty('dtc_numbers')) {
                obj['dtc_numbers'] = ApiClient.convertToType(data['dtc_numbers'], ['String']);
            }
            if (data.hasOwnProperty('oauth')) {
                obj['oauth'] = ApiClient.convertToType(data['oauth'], 'Boolean');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = SearchInstitutions200ResponseInstitutionsInnerStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchInstitutions200ResponseInstitutionsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchInstitutions200ResponseInstitutionsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['institution_id'] && !(typeof data['institution_id'] === 'string' || data['institution_id'] instanceof String)) {
            throw new Error("Expected the field `institution_id` to be a primitive type in the JSON string but got " + data['institution_id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['country_codes'])) {
            throw new Error("Expected the field `country_codes` to be an array in the JSON data but got " + data['country_codes']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['products'])) {
            throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['routing_numbers'])) {
            throw new Error("Expected the field `routing_numbers` to be an array in the JSON data but got " + data['routing_numbers']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['dtc_numbers'])) {
            throw new Error("Expected the field `dtc_numbers` to be an array in the JSON data but got " + data['dtc_numbers']);
        }
        // validate the optional field `status`
        if (data['status']) { // data not null
          SearchInstitutions200ResponseInstitutionsInnerStatus.validateJSON(data['status']);
        }

        return true;
    }


}



/**
 * @member {String} institution_id
 */
SearchInstitutions200ResponseInstitutionsInner.prototype['institution_id'] = undefined;

/**
 * @member {String} name
 */
SearchInstitutions200ResponseInstitutionsInner.prototype['name'] = undefined;

/**
 * @member {Array.<String>} country_codes
 */
SearchInstitutions200ResponseInstitutionsInner.prototype['country_codes'] = undefined;

/**
 * @member {Array.<module:model/SearchInstitutions200ResponseInstitutionsInner.ProductsEnum>} products
 */
SearchInstitutions200ResponseInstitutionsInner.prototype['products'] = undefined;

/**
 * @member {Array.<String>} routing_numbers
 */
SearchInstitutions200ResponseInstitutionsInner.prototype['routing_numbers'] = undefined;

/**
 * @member {Array.<String>} dtc_numbers
 */
SearchInstitutions200ResponseInstitutionsInner.prototype['dtc_numbers'] = undefined;

/**
 * @member {Boolean} oauth
 */
SearchInstitutions200ResponseInstitutionsInner.prototype['oauth'] = undefined;

/**
 * @member {module:model/SearchInstitutions200ResponseInstitutionsInnerStatus} status
 */
SearchInstitutions200ResponseInstitutionsInner.prototype['status'] = undefined;





/**
 * Allowed values for the <code>products</code> property.
 * @enum {String}
 * @readonly
 */
SearchInstitutions200ResponseInstitutionsInner['ProductsEnum'] = {

    /**
     * value: "assets"
     * @const
     */
    "assets": "assets",

    /**
     * value: "auth"
     * @const
     */
    "auth": "auth",

    /**
     * value: "balance"
     * @const
     */
    "balance": "balance",

    /**
     * value: "transactions"
     * @const
     */
    "transactions": "transactions",

    /**
     * value: "identity"
     * @const
     */
    "identity": "identity",

    /**
     * value: "investments"
     * @const
     */
    "investments": "investments"
};



export default SearchInstitutions200ResponseInstitutionsInner;

