/**
 * Plaid API
 * API for accessing financial institution data via Plaid.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SearchInstitutionsRequest model module.
 * @module model/SearchInstitutionsRequest
 * @version 1.0.0
 */
class SearchInstitutionsRequest {
    /**
     * Constructs a new <code>SearchInstitutionsRequest</code>.
     * @alias module:model/SearchInstitutionsRequest
     */
    constructor() { 
        
        SearchInstitutionsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchInstitutionsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchInstitutionsRequest} obj Optional instance to populate.
     * @return {module:model/SearchInstitutionsRequest} The populated <code>SearchInstitutionsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchInstitutionsRequest();

            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchInstitutionsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchInstitutionsRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['client_id'] && !(typeof data['client_id'] === 'string' || data['client_id'] instanceof String)) {
            throw new Error("Expected the field `client_id` to be a primitive type in the JSON string but got " + data['client_id']);
        }
        // ensure the json data is a string
        if (data['secret'] && !(typeof data['secret'] === 'string' || data['secret'] instanceof String)) {
            throw new Error("Expected the field `secret` to be a primitive type in the JSON string but got " + data['secret']);
        }
        // ensure the json data is a string
        if (data['query'] && !(typeof data['query'] === 'string' || data['query'] instanceof String)) {
            throw new Error("Expected the field `query` to be a primitive type in the JSON string but got " + data['query']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['products'])) {
            throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
        }

        return true;
    }


}



/**
 * @member {String} client_id
 */
SearchInstitutionsRequest.prototype['client_id'] = undefined;

/**
 * @member {String} secret
 */
SearchInstitutionsRequest.prototype['secret'] = undefined;

/**
 * @member {String} query
 */
SearchInstitutionsRequest.prototype['query'] = undefined;

/**
 * @member {Array.<module:model/SearchInstitutionsRequest.ProductsEnum>} products
 */
SearchInstitutionsRequest.prototype['products'] = undefined;





/**
 * Allowed values for the <code>products</code> property.
 * @enum {String}
 * @readonly
 */
SearchInstitutionsRequest['ProductsEnum'] = {

    /**
     * value: "auth"
     * @const
     */
    "auth": "auth",

    /**
     * value: "balance"
     * @const
     */
    "balance": "balance",

    /**
     * value: "identity"
     * @const
     */
    "identity": "identity",

    /**
     * value: "transactions"
     * @const
     */
    "transactions": "transactions",

    /**
     * value: "investments"
     * @const
     */
    "investments": "investments"
};



export default SearchInstitutionsRequest;

