/**
 * Plaid API
 * API for accessing financial institution data via Plaid.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown model module.
 * @module model/SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown
 * @version 1.0.0
 */
class SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown {
    /**
     * Constructs a new <code>SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown</code>.
     * @alias module:model/SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown
     */
    constructor() { 
        
        SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown} obj Optional instance to populate.
     * @return {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown} The populated <code>SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Number');
            }
            if (data.hasOwnProperty('error_plaid')) {
                obj['error_plaid'] = ApiClient.convertToType(data['error_plaid'], 'Number');
            }
            if (data.hasOwnProperty('error_institution')) {
                obj['error_institution'] = ApiClient.convertToType(data['error_institution'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} success
 */
SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown.prototype['success'] = undefined;

/**
 * @member {Number} error_plaid
 */
SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown.prototype['error_plaid'] = undefined;

/**
 * @member {Number} error_institution
 */
SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown.prototype['error_institution'] = undefined;






export default SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown;

