/**
 * Plaid API
 * API for accessing financial institution data via Plaid.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown model module.
 * @module model/SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown
 * @version 1.0.0
 */
class SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown {
    /**
     * Constructs a new <code>SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown</code>.
     * @alias module:model/SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown
     */
    constructor() { 
        
        SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown} obj Optional instance to populate.
     * @return {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown} The populated <code>SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Number');
            }
            if (data.hasOwnProperty('error_plaid')) {
                obj['error_plaid'] = ApiClient.convertToType(data['error_plaid'], 'Number');
            }
            if (data.hasOwnProperty('error_institution')) {
                obj['error_institution'] = ApiClient.convertToType(data['error_institution'], 'Number');
            }
            if (data.hasOwnProperty('refresh_interval')) {
                obj['refresh_interval'] = ApiClient.convertToType(data['refresh_interval'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['refresh_interval'] && !(typeof data['refresh_interval'] === 'string' || data['refresh_interval'] instanceof String)) {
            throw new Error("Expected the field `refresh_interval` to be a primitive type in the JSON string but got " + data['refresh_interval']);
        }

        return true;
    }


}



/**
 * @member {Number} success
 */
SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown.prototype['success'] = undefined;

/**
 * @member {Number} error_plaid
 */
SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown.prototype['error_plaid'] = undefined;

/**
 * @member {Number} error_institution
 */
SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown.prototype['error_institution'] = undefined;

/**
 * @member {String} refresh_interval
 */
SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown.prototype['refresh_interval'] = undefined;






export default SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown;

