/**
 * Plaid API
 * API for accessing financial institution data via Plaid.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SearchInstitutions200ResponseInstitutionsInnerStatusAuth from './SearchInstitutions200ResponseInstitutionsInnerStatusAuth';
import SearchInstitutions200ResponseInstitutionsInnerStatusIdentity from './SearchInstitutions200ResponseInstitutionsInnerStatusIdentity';
import SearchInstitutions200ResponseInstitutionsInnerStatusInvestments from './SearchInstitutions200ResponseInstitutionsInnerStatusInvestments';
import SearchInstitutions200ResponseInstitutionsInnerStatusItemLogins from './SearchInstitutions200ResponseInstitutionsInnerStatusItemLogins';
import SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates from './SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates';

/**
 * The SearchInstitutions200ResponseInstitutionsInnerStatus model module.
 * @module model/SearchInstitutions200ResponseInstitutionsInnerStatus
 * @version 1.0.0
 */
class SearchInstitutions200ResponseInstitutionsInnerStatus {
    /**
     * Constructs a new <code>SearchInstitutions200ResponseInstitutionsInnerStatus</code>.
     * @alias module:model/SearchInstitutions200ResponseInstitutionsInnerStatus
     */
    constructor() { 
        
        SearchInstitutions200ResponseInstitutionsInnerStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchInstitutions200ResponseInstitutionsInnerStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchInstitutions200ResponseInstitutionsInnerStatus} obj Optional instance to populate.
     * @return {module:model/SearchInstitutions200ResponseInstitutionsInnerStatus} The populated <code>SearchInstitutions200ResponseInstitutionsInnerStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchInstitutions200ResponseInstitutionsInnerStatus();

            if (data.hasOwnProperty('item_logins')) {
                obj['item_logins'] = SearchInstitutions200ResponseInstitutionsInnerStatusItemLogins.constructFromObject(data['item_logins']);
            }
            if (data.hasOwnProperty('transactions_updates')) {
                obj['transactions_updates'] = SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates.constructFromObject(data['transactions_updates']);
            }
            if (data.hasOwnProperty('auth')) {
                obj['auth'] = SearchInstitutions200ResponseInstitutionsInnerStatusAuth.constructFromObject(data['auth']);
            }
            if (data.hasOwnProperty('identity')) {
                obj['identity'] = SearchInstitutions200ResponseInstitutionsInnerStatusIdentity.constructFromObject(data['identity']);
            }
            if (data.hasOwnProperty('investments')) {
                obj['investments'] = SearchInstitutions200ResponseInstitutionsInnerStatusInvestments.constructFromObject(data['investments']);
            }
            if (data.hasOwnProperty('investments_updates')) {
                obj['investments_updates'] = SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates.constructFromObject(data['investments_updates']);
            }
            if (data.hasOwnProperty('liabilities_updates')) {
                obj['liabilities_updates'] = SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates.constructFromObject(data['liabilities_updates']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchInstitutions200ResponseInstitutionsInnerStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchInstitutions200ResponseInstitutionsInnerStatus</code>.
     */
    static validateJSON(data) {
        // validate the optional field `item_logins`
        if (data['item_logins']) { // data not null
          SearchInstitutions200ResponseInstitutionsInnerStatusItemLogins.validateJSON(data['item_logins']);
        }
        // validate the optional field `transactions_updates`
        if (data['transactions_updates']) { // data not null
          SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates.validateJSON(data['transactions_updates']);
        }
        // validate the optional field `auth`
        if (data['auth']) { // data not null
          SearchInstitutions200ResponseInstitutionsInnerStatusAuth.validateJSON(data['auth']);
        }
        // validate the optional field `identity`
        if (data['identity']) { // data not null
          SearchInstitutions200ResponseInstitutionsInnerStatusIdentity.validateJSON(data['identity']);
        }
        // validate the optional field `investments`
        if (data['investments']) { // data not null
          SearchInstitutions200ResponseInstitutionsInnerStatusInvestments.validateJSON(data['investments']);
        }
        // validate the optional field `investments_updates`
        if (data['investments_updates']) { // data not null
          SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates.validateJSON(data['investments_updates']);
        }
        // validate the optional field `liabilities_updates`
        if (data['liabilities_updates']) { // data not null
          SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates.validateJSON(data['liabilities_updates']);
        }

        return true;
    }


}



/**
 * @member {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusItemLogins} item_logins
 */
SearchInstitutions200ResponseInstitutionsInnerStatus.prototype['item_logins'] = undefined;

/**
 * @member {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates} transactions_updates
 */
SearchInstitutions200ResponseInstitutionsInnerStatus.prototype['transactions_updates'] = undefined;

/**
 * @member {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusAuth} auth
 */
SearchInstitutions200ResponseInstitutionsInnerStatus.prototype['auth'] = undefined;

/**
 * @member {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusIdentity} identity
 */
SearchInstitutions200ResponseInstitutionsInnerStatus.prototype['identity'] = undefined;

/**
 * @member {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusInvestments} investments
 */
SearchInstitutions200ResponseInstitutionsInnerStatus.prototype['investments'] = undefined;

/**
 * @member {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates} investments_updates
 */
SearchInstitutions200ResponseInstitutionsInnerStatus.prototype['investments_updates'] = undefined;

/**
 * @member {module:model/SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdates} liabilities_updates
 */
SearchInstitutions200ResponseInstitutionsInnerStatus.prototype['liabilities_updates'] = undefined;






export default SearchInstitutions200ResponseInstitutionsInnerStatus;

