/**
 * Plaid API
 * API for accessing financial institution data via Plaid.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SearchInstitutions200ResponseInstitutionsInner from './SearchInstitutions200ResponseInstitutionsInner';

/**
 * The SearchInstitutions200Response model module.
 * @module model/SearchInstitutions200Response
 * @version 1.0.0
 */
class SearchInstitutions200Response {
    /**
     * Constructs a new <code>SearchInstitutions200Response</code>.
     * @alias module:model/SearchInstitutions200Response
     */
    constructor() { 
        
        SearchInstitutions200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchInstitutions200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchInstitutions200Response} obj Optional instance to populate.
     * @return {module:model/SearchInstitutions200Response} The populated <code>SearchInstitutions200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchInstitutions200Response();

            if (data.hasOwnProperty('institutions')) {
                obj['institutions'] = ApiClient.convertToType(data['institutions'], [SearchInstitutions200ResponseInstitutionsInner]);
            }
            if (data.hasOwnProperty('request_id')) {
                obj['request_id'] = ApiClient.convertToType(data['request_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchInstitutions200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchInstitutions200Response</code>.
     */
    static validateJSON(data) {
        if (data['institutions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['institutions'])) {
                throw new Error("Expected the field `institutions` to be an array in the JSON data but got " + data['institutions']);
            }
            // validate the optional field `institutions` (array)
            for (const item of data['institutions']) {
                SearchInstitutions200ResponseInstitutionsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['request_id'] && !(typeof data['request_id'] === 'string' || data['request_id'] instanceof String)) {
            throw new Error("Expected the field `request_id` to be a primitive type in the JSON string but got " + data['request_id']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/SearchInstitutions200ResponseInstitutionsInner>} institutions
 */
SearchInstitutions200Response.prototype['institutions'] = undefined;

/**
 * @member {String} request_id
 */
SearchInstitutions200Response.prototype['request_id'] = undefined;






export default SearchInstitutions200Response;

