# coding: utf-8

"""
    Plaid API

    API for accessing financial institution data via Plaid.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_institutions200_response_institutions_inner_status_transactions_updates_breakdown import SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown

class TestSearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown(unittest.TestCase):
    """SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown:
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown`
        """
        model = SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown()
        if include_optional:
            return SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown(
                success = 0.95,
                error_plaid = 0.02,
                error_institution = 0.03,
                refresh_interval = 'NORMAL'
            )
        else:
            return SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown(
        )
        """

    def testSearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown(self):
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusTransactionsUpdatesBreakdown"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
