# coding: utf-8

"""
    Plaid API

    API for accessing financial institution data via Plaid.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_institutions200_response_institutions_inner_status_identity_breakdown import SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown

class TestSearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown(unittest.TestCase):
    """SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown:
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown`
        """
        model = SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown()
        if include_optional:
            return SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown(
                success = 0.42,
                error_plaid = 0.08,
                error_institution = 0.5
            )
        else:
            return SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown(
        )
        """

    def testSearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown(self):
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
