# coding: utf-8

"""
    Plaid API

    API for accessing financial institution data via Plaid.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_institutions200_response_institutions_inner_status_investments_breakdown import SearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown

class TestSearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown(unittest.TestCase):
    """SearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown:
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown`
        """
        model = SearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown()
        if include_optional:
            return SearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown(
                success = 0.89,
                error_plaid = 0.02,
                error_institution = 0.09
            )
        else:
            return SearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown(
        )
        """

    def testSearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown(self):
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusInvestmentsBreakdown"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
