# coding: utf-8

"""
    Plaid API

    API for accessing financial institution data via Plaid.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_institutions200_response_institutions_inner_status_auth import SearchInstitutions200ResponseInstitutionsInnerStatusAuth

class TestSearchInstitutions200ResponseInstitutionsInnerStatusAuth(unittest.TestCase):
    """SearchInstitutions200ResponseInstitutionsInnerStatusAuth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchInstitutions200ResponseInstitutionsInnerStatusAuth:
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusAuth
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchInstitutions200ResponseInstitutionsInnerStatusAuth`
        """
        model = SearchInstitutions200ResponseInstitutionsInnerStatusAuth()
        if include_optional:
            return SearchInstitutions200ResponseInstitutionsInnerStatusAuth(
                status = 'HEALTHY',
                last_status_change = '2019-02-15T15:53Z',
                breakdown = openapi_client.models.search_institutions_200_response_institutions_inner_status_auth_breakdown.searchInstitutions_200_response_institutions_inner_status_auth_breakdown(
                    success = 0.91, 
                    error_plaid = 0.01, 
                    error_institution = 0.08, )
            )
        else:
            return SearchInstitutions200ResponseInstitutionsInnerStatusAuth(
        )
        """

    def testSearchInstitutions200ResponseInstitutionsInnerStatusAuth(self):
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusAuth"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
