# coding: utf-8

"""
    Plaid API

    API for accessing financial institution data via Plaid.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_institutions200_response_institutions_inner_status_identity import SearchInstitutions200ResponseInstitutionsInnerStatusIdentity

class TestSearchInstitutions200ResponseInstitutionsInnerStatusIdentity(unittest.TestCase):
    """SearchInstitutions200ResponseInstitutionsInnerStatusIdentity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchInstitutions200ResponseInstitutionsInnerStatusIdentity:
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusIdentity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchInstitutions200ResponseInstitutionsInnerStatusIdentity`
        """
        model = SearchInstitutions200ResponseInstitutionsInnerStatusIdentity()
        if include_optional:
            return SearchInstitutions200ResponseInstitutionsInnerStatusIdentity(
                status = 'DEGRADED',
                last_status_change = '2019-02-15T15:50Z',
                breakdown = openapi_client.models.search_institutions_200_response_institutions_inner_status_identity_breakdown.searchInstitutions_200_response_institutions_inner_status_identity_breakdown(
                    success = 0.42, 
                    error_plaid = 0.08, 
                    error_institution = 0.5, )
            )
        else:
            return SearchInstitutions200ResponseInstitutionsInnerStatusIdentity(
        )
        """

    def testSearchInstitutions200ResponseInstitutionsInnerStatusIdentity(self):
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusIdentity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
