# coding: utf-8

"""
    Plaid API

    API for accessing financial institution data via Plaid.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_institutions200_response_institutions_inner_status_investments import SearchInstitutions200ResponseInstitutionsInnerStatusInvestments

class TestSearchInstitutions200ResponseInstitutionsInnerStatusInvestments(unittest.TestCase):
    """SearchInstitutions200ResponseInstitutionsInnerStatusInvestments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchInstitutions200ResponseInstitutionsInnerStatusInvestments:
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusInvestments
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchInstitutions200ResponseInstitutionsInnerStatusInvestments`
        """
        model = SearchInstitutions200ResponseInstitutionsInnerStatusInvestments()
        if include_optional:
            return SearchInstitutions200ResponseInstitutionsInnerStatusInvestments(
                status = 'HEALTHY',
                last_status_change = '2019-02-15T15:53Z',
                breakdown = openapi_client.models.search_institutions_200_response_institutions_inner_status_investments_breakdown.searchInstitutions_200_response_institutions_inner_status_investments_breakdown(
                    success = 0.89, 
                    error_plaid = 0.02, 
                    error_institution = 0.09, )
            )
        else:
            return SearchInstitutions200ResponseInstitutionsInnerStatusInvestments(
        )
        """

    def testSearchInstitutions200ResponseInstitutionsInnerStatusInvestments(self):
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusInvestments"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
