# coding: utf-8

"""
    Plaid API

    API for accessing financial institution data via Plaid.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_institutions200_response_institutions_inner_status_auth_breakdown import SearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown

class TestSearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown(unittest.TestCase):
    """SearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown:
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown`
        """
        model = SearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown()
        if include_optional:
            return SearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown(
                success = 0.91,
                error_plaid = 0.01,
                error_institution = 0.08
            )
        else:
            return SearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown(
        )
        """

    def testSearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown(self):
        """Test SearchInstitutions200ResponseInstitutionsInnerStatusAuthBreakdown"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
