# coding: utf-8

"""
    Plaid API

    API for accessing financial institution data via Plaid.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_institutions_request import SearchInstitutionsRequest

class TestSearchInstitutionsRequest(unittest.TestCase):
    """SearchInstitutionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchInstitutionsRequest:
        """Test SearchInstitutionsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchInstitutionsRequest`
        """
        model = SearchInstitutionsRequest()
        if include_optional:
            return SearchInstitutionsRequest(
                client_id = 'your_client_id',
                secret = 'your_sandbox_secret',
                query = 'Chase',
                products = [
                    'auth'
                    ]
            )
        else:
            return SearchInstitutionsRequest(
        )
        """

    def testSearchInstitutionsRequest(self):
        """Test SearchInstitutionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
