# coding: utf-8

"""
    Plaid API

    API for accessing financial institution data via Plaid.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.search_institutions200_response_institutions_inner_status_identity_breakdown import SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown
from typing import Optional, Set
from typing_extensions import Self

class SearchInstitutions200ResponseInstitutionsInnerStatusIdentity(BaseModel):
    """
    SearchInstitutions200ResponseInstitutionsInnerStatusIdentity
    """ # noqa: E501
    status: Optional[StrictStr] = None
    last_status_change: Optional[datetime] = None
    breakdown: Optional[SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown] = None
    __properties: ClassVar[List[str]] = ["status", "last_status_change", "breakdown"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchInstitutions200ResponseInstitutionsInnerStatusIdentity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of breakdown
        if self.breakdown:
            _dict['breakdown'] = self.breakdown.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchInstitutions200ResponseInstitutionsInnerStatusIdentity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "last_status_change": obj.get("last_status_change"),
            "breakdown": SearchInstitutions200ResponseInstitutionsInnerStatusIdentityBreakdown.from_dict(obj["breakdown"]) if obj.get("breakdown") is not None else None
        })
        return _obj


